site_name: open.ondat.io 
site_url: https://beezy.sh
theme:
  font:
    text: Red Hat Text
    code: Red Hat Mono
  logo: images/ondat_logo_darkbg.webp
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  name: material
  palette: 
    - scheme: default
      primary: black 
      accent: blue 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: black 
      accent: blue 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
extra_css: 
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/beezy-sh/refactored-lamp
    - icon: fontawesome/brands/slack
      link: https://storageos.slack.com/ 
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ondat_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ondat/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCWhaUE5K9RfkJVGrHys3xug
  generator: true
copyright: Copyright &copy; 2021 Ondat. All righ reserved. 
repo_url: https://github.com/beezy-sh/refactored-lamp
repo_name: beezy-sh/refactored-lamp

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Projects: 'index.md'
  - Contributing: 'contributing.md'
  - Discoblocks: 
    - The Intrepid Squirrel is Out!: '202112-article-the_intrepid_squirrel_is_out.md'
    - 3 Key Takeaways from KubeCon NA 2021: '202111-article-3_key_takeaways_from_kubecon_na_2021.md'
    - Documentation:
      - The Intrepid Squirrel is Out!: '202112-article-the_intrepid_squirrel_is_out.md'
      - 3 Key Takeaways from KubeCon NA 2021: '202111-article-3_key_takeaways_from_kubecon_na_2021.md'
  - Trousseau: 
    - Documentation:
      - Release Notes: 'trousseau/release_notes.md'
      - Architecture: 'trousseau/architecture.md'
      - Deployment: 'trousseau/deployment.md'
      - Operations: 'trousseau/operations.md'
      - Support: 'trousseau/support.md'
#    - Posts:
    - Community:
      - A Kubernetes ZeroTrust Model using a KMS Provider Plugin: '202206-presentation-hashiconf_europe.md'
      - How to Solve Kubernetes Secrets Conundrum : '202206-presentation-hashicorp_user_group.md'